name: Shadow
version: '${project.version}'
main: shadow.customplugin.shadow.Shadow
api-version: 1.19
authors: [ Shadow ]
description: Shadows first advanced plugin
website: main.shadow-sandbox.cf

commands:
  rules:
    description: Opens a rules gui
  trash:
    description: A trash bin
    permission: 'shadow.bin'
  term:
    description: Gives  u an terminator like bow
    permission: OP
  RulesSign:
    description: Gives u The Rules sign
  kill:
    description: Kills u
    permission-message: L kid u cannot do that
    permission: OP
  gmc:
    description: sets u to gamemode c without having to type the whole thing
    aliases: gc
    permission: OP
    permission-message: §cYou Cannot do that
  boss1:
   description: spawns a boss dodo
   permission-message: L
  sandboxitems:
    description: Opens Custom Items Menu
  hub:
    description: Teleports u to hub
  dragons:
    description: Teleports u to dragons
  sbmenu:
    description: Opens Skyblock Menu
  boss2:
    description: Spawns a strong mob
  stats:
    description: Not Implemented
  mainhologram:
    description: spawns shadow sandbox hologram
  tpmenu:
    description: Opens A tp menu GUI
  givecoins:
    description: Gives You 100000000 coins