name: Shadow
version: '${project.version}'
main: shadow.customplugin.shadow.Shadow
api-version: 1.19
authors: [ Shadow ]
description: Shadows first advanced plugin
website: main.shadow-sandbox.cf

commands:
  inventory:
    description: Opens a inventory gui
    permission: OP
    permission-message: u don't have perms idiot
  trash:
    description: A trash bin
    permission: 'shadow.bin'
  term:
    description: Gives  u an terminator like bow
    permission: OP



