name: Shadow
version: '${project.version}'
main: shadow.customplugin.shadow.Shadow
api-version: 1.19
authors: [ Shadow ]
description: Shadows first advanced plugin
website: main.shadow-sandbox.cf

commands:
  rules:
    description: Opens a rules gui
  trash:
    description: A trash bin
    permission: 'shadow.bin'
  term:
    description: Gives  u an terminator like bow
    permission: OP
  RulesSign:
    description: Gives u The Rules sign

  kill:
    description: Kills u
    permission-message: L kid u cannot do that
    permission: OP

  gmc:
    description: sets u to gamemode c without having to type the whole thing
    aliases: gc
    permission: OP
    permission-message: §cYou Cannot do that
