name: Build

on:
  push:
    branches:
    - "master"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Install Spigot 1.8.8
      run: |
         mkdir spigot
         cd spigot
         wget -O BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
         java -jar BuildTools.jar --rev 1.8.8
      
      
      
    - name: Add Jar to GitHub releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.PASSWORD }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Automatic Build from Pull Request"
        files: |
          target/*.jar
          
